### ISSUE TITLE
workflow re: console error panic hook

### ISSUE THREAD

**Issue by ashleygwilliams** [rustwasm/wasm-pack-template#11]
currently, with the wasm-pack workflow we expect folks to publish a package. however, this template includes console error panic hook as a tool for debugging wasm errors that show up in the console. people should remove this before publishing. 

how do we expect that folks run into the errors that console error panic hook would help display?
i'm having trouble imagining the scenario.

cc @fitzgen 

re #9 #10

**Comment by fitzgen** [comment]
I'm imagining that the "production" build would not enable this feature. Does that align with your expectations?

**Comment by ashleygwilliams** [comment]
ahhhhhh yes yes ok. i wasn't thinking that through but that is very helpful. great. thanks!
