### ISSUE TITLE
"The given paths are neither files nor directories!"

### ISSUE THREAD

**Issue by steveklabnik** [rustwasm/wasm-pack-template#28]
When using `cargo-generate` with this template, I get

    The given paths are neither files nor directories! "C:\\Users\\steve\\src\\oredev2018\\webassembly-deep-dive\\demo\\.genignore"

**Comment by ashleygwilliams** [comment]
this is a bug that is in cargo-generate latest published version: https://github.com/ashleygwilliams/cargo-generate/issues/116

a PR landed for is 2 days ago: https://github.com/ashleygwilliams/cargo-generate/pull/120

i can cut a release with the fix today
