### ISSUE TITLE
Hanged on `Installing wasm-bindgen`

### ISSUE THREAD

**Issue by t1anchen** [rustwasm/wasm-pack-template#44]
### Describe the Bug

The installation hangs around `Installing wasm-bindgen`.

```
$ wasm-pack build
[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
    Updating crates.io index
   Compiling proc-macro2 v1.0.0
   Compiling unicode-xid v0.2.0
   Compiling wasm-bindgen-shared v0.2.49
   Compiling log v0.4.8
   Compiling syn v1.0.1
   Compiling cfg-if v0.1.9
   Compiling bumpalo v2.5.0
   Compiling lazy_static v1.3.0
   Compiling wasm-bindgen v0.2.49
   Compiling quote v1.0.0
   Compiling wasm-bindgen-backend v0.2.49
   Compiling wasm-bindgen-macro-support v0.2.49
   Compiling wasm-bindgen-macro v0.2.49
   Compiling console_error_panic_hook v0.1.6
   Compiling wasm-game-of-life v0.1.0 (/Users/xxx/projects/wasm-game-of-life)
warning: function is never used: `set_panic_hook`
 --> src/utils.rs:1:1
  |
1 | pub fn set_panic_hook() {
  | ^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(dead_code)] on by default

    Finished release [optimized] target(s) in 54.57s
[INFO]: ⬇️  Installing wasm-bindgen...
```

### Steps to Reproduce

Follow [the Setup directives of Rust and WebAssembly book](https://rustwasm.github.io/docs/book/game-of-life/setup.html) to install the dependencies.

1. `cargo install wasm-pack` and the version of `wasm-pack` is `0.8.1`
2. `cargo install cargo-generate` and cargo-generate version is `0.4.0`
3. `npm` version is `6.10.3`
4. `cargo generate --git https://github.com/rustwasm/wasm-pack-template`
5. Type name as `wasm-game-of-life`
6. `cd wasm-game-of-life`
7. `wasm-pack build`
8. It hanged around `Installing wasm-bindgen`

I check the version of `wasm-bindgen`, which is `0.2.49`.

### Expected Behavior

It should be accomplished in a short time insteald of hanging there.

### Actual Behavior

The installation hangs around `Installing wasm-bindgen`.

### Additional Context

Additional question: Is this project alive and under maintainance?

**Comment by t1anchen** [comment]
I found an ad-hoc solution.

## Recommendations

- Change version of `wasm-bindgen` in the `dependencies` section of `Cargo.toml` to a concrete version, i.e. `wasm-bindgen = "0.2.49"`
- Try `cargo install wasm-bindgen-cli`, and the version would be *EXACTLY SAME* as the verision installed by `wasm-pack build`. i.e. if the latest `wasm-bindgen` 0.2 version is `0.2.49`, install the cli by `cargo install wasm-bindgen-cli --version 0.2.49` then rerun `wasm build`.

Hopefully this solution can be helpful for those who have same issues.

## Reference/Links

- https://github.com/rustwasm/wasm-pack/issues/308
- https://github.com/rustwasm/wasm-pack/issues/272
- https://github.com/rustwasm/wasm-pack/issues/508

**Comment by yangdonglai** [comment]
Mark

**Comment by juxuny** [comment]
Finally, I install wasm-bindgen-cli and wasm-opt before running `wasm-pack build`, I got it fixed
