### ISSUE TITLE
Why Cargo.lock is in the default .gitignore?

### ISSUE THREAD

**Issue by vlad20012** [rustwasm/wasm-pack-template#53]
### Summary

This repository contains a `.gitignore` file that is actually a part of the template, so when you apply the template with `cargo generate`, `.gitignore` appears in a user's project directory as-is.
So, why `Cargo.lock` is in the default `.gitignore` file of this template?

### Additional Details

It's common practice to commit `Cargo.lock` to a repository and `Cargo.lock` is designed to provide similar dependencies across all developer machines. Also, there are no `Cargo.lock` is the default `.gitignore` when you create a project with `cargo new`. So maybe it's not a good practice to enforce such an ignoring in a default project template?

**Comment by clemens-tolboom** [comment]
I am also a little confused about all files installed. The list on https://rustwasm.github.io/docs/book/game-of-life/hello-world.html#whats-inside is smaller then mine.

The generate result has
```
git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .appveyor.yml
        .cargo-ok
        .gitignore
        .idea/
        .travis.yml
        Cargo.toml
        LICENSE_APACHE
        LICENSE_MIT
        README.md
        src/
        tests/
```

### Delete

Guess we have to manually delete

- .appveyor.yml
- .cargo-ok
- .travis.yml
- LICENSE_APACHE
- LICENSE_MIT

### Edit

- .gitignore
- .idea/
- README.md

## End result

```
git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .gitignore
        Cargo.lock
        Cargo.toml
        README.md
        src/
        tests/
```

**Comment by protheory8** [comment]
@vlad20012 Because it's a library crate. If you make a new project with `cargo new --lib`, Cargo does add `Cargo.lock` into the `.gitignore` file.
