### ISSUE TITLE
Guys and girls, how to build and run "Hello, World" program from the "Rust and WebAssembly" book? npm says that it could not find the executable file

### ISSUE THREAD

**Issue by drogan-v** [rustwasm/wasm-pack-template#73]
➤ npm init wasm-app www
npm error could not determine executable to run

**Comment by drogan-v** [comment]
I found this one:
#https://github.com/rustwasm/create-wasm-app/issues/206#issuecomment-1519116945

**Comment by zhangr4** [comment]
> I found this one: #[rustwasm/create-wasm-app#206 (comment)](https://github.com/rustwasm/create-wasm-app/issues/206#issuecomment-1519116945)

@j4dzg3r I got the same issue here. Could you help provide mode details to resolve it. I don't know where to put `--target web`, should I run command like `npm init wasm-app www --target web`? really thanks

**Comment by drogan-v** [comment]
This comment is about a workless repo. MDN has a topic about wasm and Rust, that can help you compile your program.https://developer.mozilla.org/ru/docs/WebAssembly/Rust_to_Wasm
